# Generated by Django 2.2.11 on 2020-06-16 20:21

import Rasta_Web.utils
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('poster', models.ImageField(upload_to='event_posters/', validators=[Rasta_Web.utils.validate_image_size])),
                ('summary', models.TextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('location', models.CharField(max_length=100)),
                ('date', django_jalali.db.models.jDateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='event_photos/', validators=[Rasta_Web.utils.validate_image_size])),
                ('caption', models.CharField(blank=True, max_length=300, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
