# Generated by Django 2.2.11 on 2020-05-07 15:38

import Rasta_Web.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventphoto_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventphoto',
            name='photo',
            field=models.ImageField(upload_to='event_photos/', validators=[Rasta_Web.utils.validate_image_size]),
        ),
    ]
