# Generated by Django 2.2.11 on 2020-05-07 15:48

import Rasta_Web.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200507_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='event_documents/', validators=[Rasta_Web.utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(upload_to='event_posters/', validators=[Rasta_Web.utils.validate_image_size]),
        ),
    ]
