install: 
- "pip install -r requirements.txt"
env: 
- "DJANGO=2.2 DB=sqlite"
language: python
python: 
- "3.6"
before_script:
- cp config/database.yml.travis config/database.yml
- python manage.py makemigrations
- python manage.py migrate
- "python manage.py test"
