install: 
- "pip install -r requirements.txt"
env:
- "DJANGO=2.2 DB=postgresql"
language: python
services:
- postgresql
python: 
- "3.6"
before_script:
- psql -c 'create database test;' -U postgres
script:
- python manage.py migrate
- "python manage.py test"
