# Generated by Django 2.2.11 on 2020-06-16 20:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', ckeditor.fields.RichTextField()),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='')),
                ('intro', ckeditor.fields.RichTextField()),
                ('title', models.CharField(max_length=100)),
                ('button_link', models.URLField()),
                ('button_name', models.CharField(max_length=50)),
                ('show_on_homepage', models.BooleanField(default=True)),
            ],
        ),
    ]
