# Generated by Django 2.2.11 on 2020-03-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagedata',
            name='logo',
        ),
    ]
