# Generated by Django 2.2.11 on 2020-04-14 13:21

import ckeditor.fields
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('title', models.CharField(max_length=100)),
                ('publish_date', django_jalali.db.models.jDateTimeField()),
                ('summary', models.TextField(blank=True, max_length=300, null=True)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='blog_posts', to='blog.Category')),
            ],
        ),
    ]
