# Generated by Django 2.2.11 on 2020-04-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
