# Generated by Django 2.2.11 on 2020-04-15 23:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200415_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='summary',
            field=models.TextField(default='salam', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=ckeditor.fields.RichTextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(default='good', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
