# Generated by Django 2.2.11 on 2020-04-11 13:21

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200411_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publish_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
