# Generated by Django 2.2.11 on 2020-04-11 13:26

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200411_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publish_date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
