# Generated by Django 2.2.11 on 2020-05-07 15:48

import Rasta_Web.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200421_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', validators=[Rasta_Web.utils.validate_image_size]),
        ),
        migrations.CreateModel(
            name='BlogDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='blog_documents/', validators=[Rasta_Web.utils.validate_file_size])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost')),
            ],
        ),
    ]
