# Generated by Django 2.2.11 on 2020-06-12 10:58

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200507_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('author_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='publish_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('author_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('show', models.BooleanField(default=True)),
                ('is_admin_reply', models.BooleanField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost'),
        ),
    ]
