# Generated by Django 2.2.11 on 2020-04-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200411_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(related_name='blog_posts', to='blog.Category'),
        ),
    ]
