# Generated by Django 2.2.11 on 2020-04-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200411_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
