# Generated by Django 2.2.11 on 2020-06-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RastaMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_visible', models.ImageField(upload_to='')),
                ('photo_hidden', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('student', 'دانش آموز'), ('teacher', 'آموزگار'), ('parent', 'پدر یا مادر'), ('other', 'دیگر')], max_length=200)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
