# Generated by Django 2.2.11 on 2020-04-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='type',
            field=models.CharField(choices=[('student', 'دانش آموز'), ('teacher', 'آموزگار'), ('parent', 'پدر یا مادر'), ('other', 'دیگر')], max_length=200),
        ),
    ]
