# Generated by Django 2.2.11 on 2020-06-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='unique_id',
            field=models.CharField(default='59a10ac9d3054a9ba0c20938728e2ef6', max_length=200, unique=True),
        ),
    ]
