# Generated by Django 2.2.11 on 2020-06-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='date_joint',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
