# Generated by Django 2.2.11 on 2020-06-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20200612_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='date_joint',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
