# Generated by Django 2.2.11 on 2020-06-27 22:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20200623_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
