# Generated by Django 2.2.11 on 2020-06-12 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20200612_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='date_joint',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
