# Generated by Django 2.2.11 on 2020-06-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_auto_20200612_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtext',
            name='image',
        ),
        migrations.AlterField(
            model_name='emailtext',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
