# Generated by Django 2.2.11 on 2020-06-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_auto_20200612_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtext',
            name='link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='emailtext',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emailtext',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
