# Generated by Django 2.2.11 on 2020-06-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_auto_20200612_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtext',
            name='link_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
