# Generated by Django 2.2.11 on 2020-06-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0011_auto_20200612_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='unique_id',
            field=models.CharField(default='c42b374d451544e287e43f08616d708e', max_length=200),
        ),
    ]
