# Generated by Django 2.2.11 on 2020-06-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0012_subscriber_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='unique_id',
            field=models.CharField(default='eb94683307fc4e6d869ad1e162754eeb', max_length=200, unique=True),
        ),
    ]
